import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import AboutMe from "@/components/AboutMe";
import Contact from "@/components/Contact";
import Education from "@/components/Education";
import WorkExperience from "@/components/WorkExperience";
import Skills from "@/components/Skills";

import { Image } from "@chakra-ui/react";

import { Box, VStack } from "@chakra-ui/react";
import Projects from "@/components/Projects";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Parisa Talebi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Box boxSize="sm">
            <Image src="/p.jfif" alt="Parisa Talebi" borderRadius={50} />
          </Box>
          <h1
            style={{ fontWeight: "bold", fontSize: "60px", color: "#5271ff" }}
          >
            پریسا طالبی
          </h1>
          <h2 style={{ fontWeight: "bold", fontSize: "24px", color: "purple" }}>
            Front-End developer
          </h2>
        </div>
        <Box
          p={8}
          style={{
            direction: "rtl",
            background: "linear-gradient(#94b9ff, #cdffd8)",
          }}
        >
          <VStack align="start" spacing={6} mb={8}>
            <AboutMe />
            <Education />
            <WorkExperience />
            <Skills />
            <Contact />
          </VStack>
          <Projects />
        </Box>
      </main>
    </>
  );
}
